// utils/courses.js
export const coursesByDepartment = {
  "Computer Engineering": [
    "Introduction to Programming",
    "Data Structures and Algorithms",
    "Computer Networks",
    "Database Systems",
    "Software Engineering",
    "Operating Systems",
    "Web Development",
    "Mobile App Development",
    "Artificial Intelligence",
    "Machine Learning",
    "Computer Graphics",
    "Cybersecurity",
    "Cloud Computing",
    "Internet of Things",
    "Digital Signal Processing"
  ],
  "Electrical Engineering": [
    "Circuit Analysis",
    "Electromagnetic Fields",
    "Power Systems",
    "Control Systems",
    "Digital Electronics",
    "Analog Electronics",
    "Microprocessors",
    "Power Electronics",
    "Renewable Energy",
    "Communication Systems",
    "Signal Processing",
    "Embedded Systems",
    "Instrumentation",
    "High Voltage Engineering",
    "Electrical Machines"
  ],
  "Mechanical Engineering": [
    "Thermodynamics",
    "Fluid Mechanics",
    "Heat Transfer",
    "Materials Science",
    "Dynamics",
    "Strength of Materials",
    "Machine Design",
    "Manufacturing Processes",
    "CAD/CAM",
    "Robotics",
    "Automotive Engineering",
    "Aerospace Engineering",
    "Mechatronics",
    "HVAC Systems",
    "Quality Control"
  ],
  "Civil Engineering": [
    "Structural Analysis",
    "Concrete Technology",
    "Steel Structures",
    "Geotechnical Engineering",
    "Transportation Engineering",
    "Environmental Engineering",
    "Construction Management",
    "Surveying",
    "Hydraulics",
    "Urban Planning",
    "Building Services",
    "Coastal Engineering",
    "Earthquake Engineering",
    "Bridge Engineering",
    "Foundation Engineering"
  ],
  "Business Administration": [
    "Principles of Management",
    "Marketing Management",
    "Financial Accounting",
    "Managerial Economics",
    "Business Law",
    "Operations Management",
    "Human Resource Management",
    "Strategic Management",
    "International Business",
    "Entrepreneurship",
    "Business Ethics",
    "Corporate Finance",
    "Supply Chain Management",
    "Project Management",
    "Business Analytics"
  ],
  "Economics": [
    "Microeconomics",
    "Macroeconomics",
    "Econometrics",
    "Development Economics",
    "International Economics",
    "Public Finance",
    "Monetary Economics",
    "Labor Economics",
    "Environmental Economics",
    "Industrial Economics",
    "Agricultural Economics",
    "Health Economics",
    "Behavioral Economics",
    "Game Theory",
    "Economic History"
  ],
  "Law": [
    "Constitutional Law",
    "Criminal Law",
    "Contract Law",
    "Tort Law",
    "Property Law",
    "Administrative Law",
    "International Law",
    "Human Rights Law",
    "Environmental Law",
    "Corporate Law",
    "Family Law",
    "Intellectual Property Law",
    "Tax Law",
    "Labor Law",
    "Criminal Procedure"
  ],
  "Medicine": [
    "Anatomy",
    "Physiology",
    "Biochemistry",
    "Pathology",
    "Pharmacology",
    "Microbiology",
    "Internal Medicine",
    "Surgery",
    "Pediatrics",
    "Obstetrics & Gynecology",
    "Psychiatry",
    "Radiology",
    "Dermatology",
    "Ophthalmology",
    "Orthopedics"
  ],
  "Education": [
    "Educational Psychology",
    "Curriculum Development",
    "Teaching Methods",
    "Educational Technology",
    "Classroom Management",
    "Assessment and Evaluation",
    "Special Education",
    "Educational Administration",
    "Counseling Psychology",
    "Adult Education",
    "Distance Learning",
    "Educational Research",
    "Philosophy of Education",
    "Sociology of Education",
    "Comparative Education"
  ]
};

export const getCoursesForDepartment = (department) => {
  return coursesByDepartment[department] || [];
};